### ISSUE TITLE
Making Changes

### ISSUE THREAD

**Issue by StephanieKWilliams** [themefisher/Constra-Bootstrap-Construction-Template#3]
Hello, I downloaded your  free template for personal use but everytime i make some changes on it and run the website later on ,it reverts all changes i had made and goes back to the original template kindly assist

**Comment by tfrubel** [comment]
@StephanieKWilliams are you still facing the issue ? If you still facing Make sure to change repository link after you fork/clone this template and commit the latest changes to your current repository.
